pipeline{
    any agent

    environment {
        IMAGE_NAME = "manoj_s/microservices-platform/api-gateway:${GIT_COMMIT}"
    }

    stages{
        stage('Git Checkout'){
            steps{
                git url: 'https://github.com/KubeNexa/api-gateway.git' , branch: 'main'
            }
        }

        stage('Run Unit Tests'){
            steps{
                sh 'npm test'
            }
        }

        stage('Build Docker Image'){
            steps{
                sh '''
                    printenv
                    docker build -t ${IMAGE_NAME} .
                '''
            }
        }

        stage('Login to Docker Hub'){
            steps{
                withCredentials([usernamePassword(
                    credentialsId: 'docker-hub-credentials', 
                    usernameVariable: 'DOCKER_USERNAME', 
                    passwordVariable: 'DOCKER_PASSWORD'
                    )]) 
                    {
                    sh 'echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin'
                }
            }
        }

        stage('Push Docker Image to DockerHub'){
            steps{
                sh 'docker push ${IMAGE_NAME}'
            }
        }

        stage('Update GitOps Deployment'){
            steps{
                withCredentials([usernamePassword(
                    credentialsId: 'gitops-repo-credentials', 
                    usernameVariable: 'GITOPS_USERNAME', 
                    passwordVariable: 'GITOPS_PASSWORD'
                    )]) 
                    {
                    sh '''
                        if [ -d "gitops" ]; then
                            echo "Directory exists, removing it..."
                            rm -rf gitops
                        fi
                        git clone https://$GITOPS_USERNAME:$GIT_PASSWORD@github.com/KubeNexa/GitOps.git gitops
                        cd gitops/
                        else
                            git clone https://$GITOPS_USERNAME:$
                        git config --global user.email "

    }